homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_name
  longitude: !secret longitude_name
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: -1
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
# Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: https://djkosmix.nl:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  cors_allowed_origins: 
   - https://djkosmix.nl:7080
   - http://192.168.2.4:7080
  trusted_networks:
   - 192.168.0.0/16
   - 127.0.0.1

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
recorder:
  purge_keep_days: 5
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.2.4:3218
  terminal:
    title: Terminal
    icon: mdi:console-line
    url: http://192.168.2.4:7681
ring:
  username: arjen.kos@gmail.com
  password: !secret ring_password
  
nest:
  client_id: !secret client_id
  client_secret: !secret client_secret

zwave:
  usb_path: /dev/ttyACM0


# Weather prediction
sensor:
  - platform: pvoutput
    system_id: 54709
    api_key: kosmix-solar
    scan_interval: 150
  - platform: template
    sensors:
      power_generation:
        value_template: '{% if is_state_attr("sensor.pvoutput", "power_generation", "NaN") %}0{% else %}{{ states.sensor.pvoutput.attributes.power_generation }}{% endif %}'
        friendly_name: 'Generating'
        unit_of_measurement: 'Watt'
      energy_generation:
        value_template: '{% if is_state_attr("sensor.pvoutput", "energy_generation", "NaN") %}0{% else %}{{ "%0.2f"|format(states.sensor.pvoutput.attributes.energy_generation|float/1000) }}{% endif %}'
        friendly_name: 'Generated'
        unit_of_measurement: 'kWh'   
  - platform: dsmr
    port: /dev/ttyUSB0
    dsmr_version: 4
# Weather prediction
  - platform: yr
# Ring doorbell
  - platform: ring
camera:
  - platform: ring
# Text to speech
tts:
  - platform: google
#Binary sensor
binary_sensor:
  - platform: ring
# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
